"use client";

import { useOne, useList } from "@refinedev/core";
import { useParams } from "next/navigation";
import { Loader2 } from "lucide-react";

// Components
import { TranscriptHeader } from "./components/transcript/header";
import { StudentInfo } from "./components/transcript/student-info";
import { AcademicHistory } from "./components/transcript/academic-history";

export const StudentTranscriptView = () => {
  const { id } = useParams();
  const studentId = id as string;

  const { query: userQuery } = useOne({
    resource: "users",
    id: studentId,
  });
  const student = userQuery?.data?.data as
    | { id: string; name: string; yearLevel?: number; section?: string }
    | undefined;

  const { query: enrollmentQuery } = useList({
    resource: "enrollments",
    filters: [{ field: "studentId", operator: "eq", value: studentId }],
  });
  const enrollments = enrollmentQuery?.data?.data || [];

  const calculateGWA = () => {
    if (!enrollments.length) return "N/A";
    const grades = enrollments
      .map((e) => e.grade)
      .filter((g) => g !== null && g !== undefined) as number[];
    if (!grades.length) return "N/A";

    const sum = grades.reduce((a, b) => a + b, 0);
    const average = sum / grades.length;
    return average.toFixed(2);
  };

  if (userQuery.isLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-[60vh] gap-4">
        <Loader2 className="h-12 w-12 animate-spin text-primary opacity-20" />
        <p className="text-muted-foreground font-bold animate-pulse uppercase tracking-widest text-xs">
          Loading Academic Records...
        </p>
      </div>
    );
  }

  if (!student) {
    return (
      <div className="container mx-auto p-12 text-center">
        <h2 className="text-2xl font-bold text-destructive">
          Student Not Found
        </h2>
        <p className="text-muted-foreground">
          The requested academic record cannot be located.
        </p>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-4 space-y-8 max-w-6xl py-12">
      <TranscriptHeader />
      <StudentInfo student={student} gwa={calculateGWA()} />
      <AcademicHistory enrollments={enrollments} />

      <div className="pt-12 text-center">
        <p className="text-[10px] text-muted-foreground font-bold uppercase tracking-[0.2em] opacity-40">
          This document is generated by the Academic Infrastructure Suite
        </p>
        <p className="text-[10px] text-muted-foreground font-bold uppercase tracking-[0.2em] opacity-40">
          System Authentication Code:{" "}
          {String(student.id)?.split("-").pop()?.toUpperCase() ?? "OFFICIAL"}
        </p>
      </div>
    </div>
  );
};
